name: START-UPS
favicon: null
layout_spectrum: 0.7520565260201693
typography_spectrum: 0.38545569544658065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9113369900733232
  lightness: 0.4071598765440285
  saturation: 0.1700661494396627
  rhythmicContrast: 0.2794727021828294
purpose: []
